# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("font.size.variable.ar", 10);
user_pref("font.size.variable.el", 10);
user_pref("font.size.variable.he", 10);
user_pref("font.size.variable.ja", 10);
user_pref("font.size.variable.ko", 10);
user_pref("font.size.variable.th", 10);
user_pref("font.size.variable.tr", 10);
user_pref("font.size.variable.x-baltic", 10);
user_pref("font.size.variable.x-central-euro", 10);
user_pref("font.size.variable.x-cyrillic", 10);
user_pref("font.size.variable.x-unicode", 10);
user_pref("font.size.variable.x-western", 10);
user_pref("font.size.variable.zh-CN", 10);
user_pref("font.size.variable.zh-HK", 10);
user_pref("font.size.variable.zh-TW", 10);
user_pref("general.useragent", "Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en)");
user_pref("general.useragent.AppName", "AppleWebKit/420+ (KHTML, like Gecko)");
user_pref("general.useragent.AppVersion", "Version/3.0 Mobile/1A543a Safari/419.3");
user_pref("general.useragent.description", "iPhone");
user_pref("general.useragent.extra.firefox", "iPhone");
user_pref("general.useragent.platform", "Mobile/1A542a Safari/419.3");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-15, TIS-620, ISO-8859-2");
