#!/bin/sh
set -e
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  screenlets.public screenlets.private
fi
# End automatically added section

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
fi
# End automatically added section

if [ "$1" = "configure" ] && [ -x "`which compiz 2>/dev/null`" ]; then
	# For screenlets not to hide on "show desktop"
	gconftool --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults /apps/compiz/general/allscreens/options/hide_skip_taskbar_windows -t bool -s false
fi
