#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = "configure" ] && [ -x "`which compiz 2>/dev/null`" ]; then
	# For screenlets not to hide on "show desktop"
	gconftool --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults /apps/compiz/general/allscreens/options/hide_skip_taskbar_windows -t bool -s false
fi


